# 授权码交换令牌
POST http://localhost:9000/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&code=AxI8t_s422W9sfcaUaE_cAtu3wg0Ftor6Tsn6MSD-3zq7tpa59pj712rolnyeoY-vtBmth_1kr9bz2wHlf3EKZHVSjPWQs2PbaPqytkLdSqp8wP4l7BEoFF7ot004d8u&client_id=yyit&client_secret=23456&redirect_uri=https%3A%2F%2Foidcdebugger.com%2Fdebug

###

# 令牌自省

POST http://localhost:9000/oauth2/introspect
Content-Type: application/x-www-form-urlencoded

client_id=yyit&client_secret=123456&token=eyJraWQiOiI3MjRlMWNhOS0xN2VkLTQxZTQtYjhlNy1iMWE4NGU2ZGM2Y2MiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6Inl5aXQiLCJuYmYiOjE2NDkzMDM4MTYsInNjb3BlIjpbIm9wZW5pZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTY0OTMwNDExNiwiaWF0IjoxNjQ5MzAzODE2fQ.swROY0-40lyNxSUCNOeSYmS7NB4rpgVU5QC79PPRNFO7OhEm2h0VdIXJuIRFIwgLbLlGsVZW8403rFmFuGf6bSukEQxXAsz77M1ims6WKrvidseRWDDmEDDOFbJQtP8T0lvi3t8csQh_HnlCrF1stPQhufVkjBpNqQq3tIHo7zXwL69l-oFGDDNYJT_CA2TlY6SczrjTVLlFkclqqeF8kS-W-yt3vgREEwhpnWSh4CWkrOibnQ_5L800j3fl65BdgX937DQ3KD_OW8f8JvUHxcBEVt3I_LvX11UlDF3FGHJz0ZViHILCr5lFAeqdzvAuZTS-FRaTErlHX7Kc1WZLWg

###

# 注销访问令牌

POST http://localhost:9000/oauth2/revoke
Content-Type: application/x-www-form-urlencoded

client_id=yyit&client_secret=123456&token=eyJraWQiOiI3MjRlMWNhOS0xN2VkLTQxZTQtYjhlNy1iMWE4NGU2ZGM2Y2MiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6Inl5aXQiLCJuYmYiOjE2NDkzMDM4MTYsInNjb3BlIjpbIm9wZW5pZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTY0OTMwNDExNiwiaWF0IjoxNjQ5MzAzODE2fQ.swROY0-40lyNxSUCNOeSYmS7NB4rpgVU5QC79PPRNFO7OhEm2h0VdIXJuIRFIwgLbLlGsVZW8403rFmFuGf6bSukEQxXAsz77M1ims6WKrvidseRWDDmEDDOFbJQtP8T0lvi3t8csQh_HnlCrF1stPQhufVkjBpNqQq3tIHo7zXwL69l-oFGDDNYJT_CA2TlY6SczrjTVLlFkclqqeF8kS-W-yt3vgREEwhpnWSh4CWkrOibnQ_5L800j3fl65BdgX937DQ3KD_OW8f8JvUHxcBEVt3I_LvX11UlDF3FGHJz0ZViHILCr5lFAeqdzvAuZTS-FRaTErlHX7Kc1WZLWg

###

# 访问受保护方法
GET http://localhost:9000/private
Content-Type: application/json
Authorization: Bearer eyJraWQiOiI2YjYwNDU1Mi0yYTgyLTQyMTYtOTA4ZS0zZjcwNjZmYzY2ZjciLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoieXlpdCIsIm5iZiI6MTY0OTgxNDI0MSwic2NvcGUiOlsib3BlbmlkIl0sImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNjQ5ODE0NTQxLCJpYXQiOjE2NDk4MTQyNDF9.FDrRs6jnSzX4rThEw1881yEqU68s_NUDa9qMxG28AlvnxcJXv2CZffVOggUoel7TY0MSsB_MR-e0OJ-RPSedVjHjn_KOnhu34M4Z6G0DxawGBDCRAtmk7D8D7uWXmtOkSEoG-ZCWK9c48ePdU0XXT9QTE6xcuHU4212KaKoqesv5k76MJmc2kZGriVQEtKYXRG9qWDbZVnsyGhkRJdM4GsajpXefKNdtJewn6flrwjq6B0PolSrsBDqtXgwq-CT1FiSw__OiRyXYFBuVFX94_LtYjGZqendbm5kWITvRSACOpkvrPrY5Sa39ZC2mYbgbgEmGKUEBobqLN5JGk68OqQ


###