
http://localhost:9000/oauth2/authorize?client_id=yyit&response_type=code&redirect_uri=https://www.baidu.com&scope=openid

###

# 授权码交换令牌
POST http://localhost:9000/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic eXlpdDoxMjM0NTY=

grant_type=authorization_code&redirect_uri=https%3A%2F%2Fwww.baidu.com&code=Unj8AyzkEXwCzYP_R4qBY0xhmCWEp95qo9Rpnn7IS7KSRG1_YNwQ_04c18fPToL6EYlYteDztRO5Jp_pmG8xT_VpZxeB0yAC86nver2ifaLOjQPkakwn_6zS3_AlOpKN

###

# 令牌自省

POST http://localhost:9000/oauth2/introspect
Content-Type: application/x-www-form-urlencoded

client_id=yyit&client_secret=123456&token=eyJraWQiOiIxNmY3OGNjZC0zMTg0LTRhODEtOGQzNi1jYTBhYzJkOTE2ZTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoieXlpdCIsIm5iZiI6MTY1MjI1NTU4Nywic2NvcGUiOlsib3BlbmlkIl0sImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNjUyMjU1ODg3LCJpYXQiOjE2NTIyNTU1ODd9.ZAZHfDEFzoKjIS7y58-VAN-OSJE5g1lc_YkhsC1PHN01AAGZ6zaAmipoR_WrUhZ3OTyJsSKViNIAcR4TWeLSVps5HPjunZxMclqO_pvNft9qFspWVfs0iaMbE0X_6m3S_CX-urStVJ0ZDVf6Bs5mMvbY6GFdEZD0K0ObHtMgBXYB6OwlakeJddWHQRVOXWWh6kuvDi2AcZnCuv03zyWXpv1R--rLbSebZI0ZFnBdgtuNGbPsnUPGFWjW-OlHIJGsz4jhnugQj2A4CmHETiEwMIEoAvVFYNXSQ3KnejgnOhdQNT1vmuUutWQ5pj4qx7v8YTJ6BUr-y9foB2DhWKbG2Q

###

# 注销访问令牌

POST http://localhost:9000/oauth2/revoke
Content-Type: application/x-www-form-urlencoded

client_id=yyit&client_secret=123456&token=eyJraWQiOiIxNmY3OGNjZC0zMTg0LTRhODEtOGQzNi1jYTBhYzJkOTE2ZTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoieXlpdCIsIm5iZiI6MTY1MjI1NTU4Nywic2NvcGUiOlsib3BlbmlkIl0sImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNjUyMjU1ODg3LCJpYXQiOjE2NTIyNTU1ODd9.ZAZHfDEFzoKjIS7y58-VAN-OSJE5g1lc_YkhsC1PHN01AAGZ6zaAmipoR_WrUhZ3OTyJsSKViNIAcR4TWeLSVps5HPjunZxMclqO_pvNft9qFspWVfs0iaMbE0X_6m3S_CX-urStVJ0ZDVf6Bs5mMvbY6GFdEZD0K0ObHtMgBXYB6OwlakeJddWHQRVOXWWh6kuvDi2AcZnCuv03zyWXpv1R--rLbSebZI0ZFnBdgtuNGbPsnUPGFWjW-OlHIJGsz4jhnugQj2A4CmHETiEwMIEoAvVFYNXSQ3KnejgnOhdQNT1vmuUutWQ5pj4qx7v8YTJ6BUr-y9foB2DhWKbG2Q

###

# 访问受保护方法
GET http://localhost:9000/private
Content-Type: application/json
Authorization: Bearer eyJraWQiOiIxNmY3OGNjZC0zMTg0LTRhODEtOGQzNi1jYTBhYzJkOTE2ZTgiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoieXlpdCIsIm5iZiI6MTY1MjI1NTU4Nywic2NvcGUiOlsib3BlbmlkIl0sImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNjUyMjU1ODg3LCJpYXQiOjE2NTIyNTU1ODd9.ZAZHfDEFzoKjIS7y58-VAN-OSJE5g1lc_YkhsC1PHN01AAGZ6zaAmipoR_WrUhZ3OTyJsSKViNIAcR4TWeLSVps5HPjunZxMclqO_pvNft9qFspWVfs0iaMbE0X_6m3S_CX-urStVJ0ZDVf6Bs5mMvbY6GFdEZD0K0ObHtMgBXYB6OwlakeJddWHQRVOXWWh6kuvDi2AcZnCuv03zyWXpv1R--rLbSebZI0ZFnBdgtuNGbPsnUPGFWjW-OlHIJGsz4jhnugQj2A4CmHETiEwMIEoAvVFYNXSQ3KnejgnOhdQNT1vmuUutWQ5pj4qx7v8YTJ6BUr-y9foB2DhWKbG2Q


###