# 授权码交换令牌
POST http://localhost:9000/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&code=5bLQu_s_fNOr4z566zx4d5MnGMu-Ytbp3u0_nvuwXY9295-l9_KlvpIEIeM-VwiNviTVSfwCMuIPvyG23JxZWx4WqRxvhykbcVkaX1DEIZfvVCPgIF3t254YKJyzMW68&client_id=yyit&client_secret=123456&redirect_uri=https%3A%2F%2Foidcdebugger.com%2Fdebug

###

# 令牌自省

POST http://localhost:9000/oauth2/introspect
Content-Type: application/x-www-form-urlencoded

client_id=yyit&client_secret=123456&token=eyJraWQiOiI3M2U3OGQ2Ni1iNzM1LTQ1MGItYTc4NS02Y2E2MTNlM2Q5ZmMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6Inl5aXQiLCJuYmYiOjE2NDkzMDEzMzIsInNjb3BlIjpbIm9wZW5pZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTY0OTMwMTYzMiwiaWF0IjoxNjQ5MzAxMzMyfQ.4niWt5zsQlbDI6fCoAzMIpIoF6_zuTPhIalgrHI229Na1K89bDpsetoTDIPYwAIcD35TB6tYz5S2Rc0HQSKvSH_MXyT2Q2_1cL8G7ov0VrckyImsV8PbUJ4NsZ3r-JXhykYnZdkEgEw2gBapy2cNyvMka_JgR-QndM0lhLFWwJC_NcyGQz-7RaYjSBu6GzQmDq6rD4BJuWy6UKXj85jzIypbTF5dv1nScQXGTc9xDeWjqP0JN0tKj8vsIDdCtZjBTJemhxsgLW-TZcNq85yvIcgv3om6lqwpXwEDH3EbPz73E_WsMyFNFidTfP1F3tFl3lXp9iCPqQvv5Sk6w2mWpw

###

# 注销访问令牌

POST http://localhost:9000/oauth2/revoke
Content-Type: application/x-www-form-urlencoded

client_id=yyit&client_secret=123456&token=eyJraWQiOiI3M2U3OGQ2Ni1iNzM1LTQ1MGItYTc4NS02Y2E2MTNlM2Q5ZmMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6Inl5aXQiLCJuYmYiOjE2NDkzMDEzMzIsInNjb3BlIjpbIm9wZW5pZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTY0OTMwMTYzMiwiaWF0IjoxNjQ5MzAxMzMyfQ.4niWt5zsQlbDI6fCoAzMIpIoF6_zuTPhIalgrHI229Na1K89bDpsetoTDIPYwAIcD35TB6tYz5S2Rc0HQSKvSH_MXyT2Q2_1cL8G7ov0VrckyImsV8PbUJ4NsZ3r-JXhykYnZdkEgEw2gBapy2cNyvMka_JgR-QndM0lhLFWwJC_NcyGQz-7RaYjSBu6GzQmDq6rD4BJuWy6UKXj85jzIypbTF5dv1nScQXGTc9xDeWjqP0JN0tKj8vsIDdCtZjBTJemhxsgLW-TZcNq85yvIcgv3om6lqwpXwEDH3EbPz73E_WsMyFNFidTfP1F3tFl3lXp9iCPqQvv5Sk6w2mWpw

###


# 使用客户端凭证授权模式
POST http://localhost:9000/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=yyitjava1&client_secret=123
###
